apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: payment
    tire: app
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment
  labels:
    project: roboshop
    environment: dev
    component: payment
    tire: app
type: Opaque
data:
  AMQP_USER: "cm9ib3Nob3A="
  AMQP_PASS: "cm9ib3Nob3AxMjM="
---
apiVersion: v2
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: payment
    tire: app
spec:
  selector:
    project: roboshop
    environment: dev
    component: payment
    tire: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: payment
    tire: app
spec:
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: payment
      tire: app
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: payment
        tire: app
    spec:
      containers:
      - name: shipping
        image: ramslella/shipping:v2
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        envFrom:
          - configMapRef:
              name: payment
          - secretRef:
              name: payment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
