apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: app
    component: cart
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labeles:
    project: roboshop
    environment: dev
    tire: app
    component: cart
spec:
  selector:
    project: roboshop
    environment: dev
    tire: app
    component: cart
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: app
    component: cart
spec:
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tire: app
      component: cart
  template:
    metadata:
      labeles:
        project: roboshop
        environment: dev
        tire: app
        component: cart
    spec:
      containers:
      - name: cart
        image: ramslella/cart:v2
        envRef:
        - configMapRef:
          name: cart
        resources:
          requests:
            cpu: "64m"
            stroge: "100Mi"
          limits:
            cpu: "128m"
            stroge: "150Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10