apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    compoent: mysql
    environment: dev
    tier: database
spec:
  data:
     MYSQL_ROOT_PASSWORD: "Um9ib3Nob3BAMQ=="

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    compoent: mysql
    environment: dev
    tier: database
spec:
  selectors:
    project: roboshop
    compoent: mysql
    environment: dev
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    project: roboshop
    compoent: mysql
    environment: dev
    tier: database
spec:
  clusterIP: none
  selectors:
    project: roboshop
    compoent: mysql
    environment: dev
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    compoent: mysql
    environment: dev
    tier: database
spec:
  selector:
    matchLabels:
      project: roboshop
      compoent: mysql
      environment: dev
      tier: database
  serviceName: "mysql-headless"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        project: roboshop
        compoent: mysql
        environment: dev
        tier: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: ramslella/mysql:v2
        envFrom:
        - secretRef:
            name: mysql
        resources:
          requests:
            memory: "100Mi"
            cpu: "256m"
          limits:
            memory: "200Mi"
            cpu: "512m"
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ""
      resources:
        requests:
          storage: 2Gi
---
