apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: mongodb
    environment: dev
    tire: database
spec:
  clusterIP: None
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      environment: dev
      tire: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
   project: mongodb
   environment: dev
   tire: database 
spec:
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      environment: dev
      tire: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    environment: dev
    tire: database
spec:
  replicas: 3
  serviceName: "mongodb-headless"
  selector:
    matchLabels:
      project: mongodb
      environment: dev
      tire: database
  template:
    metadata:
      name: mongodb
      labels:
        project: mongodb
        environment: dev
        tire: database
    spec:
      containers:
      - name: mongodb
        image: ramslella/mongodb:v1
        volumeMounts:
        - name: mongodb-data
          mountpath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi