apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: shipping
    tire: backend
data:
  CART_ENDPOINT: cart:8080
  DB_HOST: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: shipping
    tire: backend
spec:
  selector:
    project: roboshop
    environment: dev
    component: shipping
    tire: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: shipping
    tire: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: shipping
      tire: backend
  template:
    metadata:
      name: shipping
      namespace: roboshop
      labels:
        project: roboshop
        environment: dev
        component: shipping
        tire: backend
    spec:
      containers:
      - name: shipping
        image: ramslella/shipping:v2
        resources:
          requests:
            memory: "150Mi"
            cpu: "256m"
          limits:
            memory: "250Mi"
            cpu: "512m"
        envFrom:
        - configMapRef:
            name: shipping
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: shipping
    tire: backend
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10