apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    envvironment: dev
    tier: app
spec:
  selector:
    project: roboshop
    component: cart
    envvironment: dev
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targrtPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata::
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    envvironment: dev
    tier: app
spec:
  selector:
    matchLabels:
      project: roboshop
      component: cart
      envvironment: dev
      tier: app
  template:
    metadata:
      name: cart
      namespace: roboshop
      labels:
        project: roboshop
        component: cart
        envvironment: dev
        tier: app
    spec:
      containers:
      - name: cart
        image: ramslella/cart:v2
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits: 
            cpu: "150m"
            memory: "256Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50    